//
//Copyright 2026 The Crossplane Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/pipeline/v1alpha1/pipeline_inspector.proto

//buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmitRequestRequest wraps the function request with correlation metadata.
type EmitRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original function request as JSON bytes (with credentials stripped for security).
	// This allows consumers to parse the request without needing the proto schema.
	Request []byte `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Metadata for correlation and identification.
	Meta          *StepMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequestRequest) Reset() {
	*x = EmitRequestRequest{}
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequestRequest) ProtoMessage() {}

func (x *EmitRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequestRequest.ProtoReflect.Descriptor instead.
func (*EmitRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *EmitRequestRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *EmitRequestRequest) GetMeta() *StepMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EmitRequestResponse is empty - this is a fire-and-forget call.
type EmitRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequestResponse) Reset() {
	*x = EmitRequestResponse{}
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequestResponse) ProtoMessage() {}

func (x *EmitRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequestResponse.ProtoReflect.Descriptor instead.
func (*EmitRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP(), []int{1}
}

// EmitResponseRequest wraps the function response with correlation metadata.
type EmitResponseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The function response as JSON bytes (nil if function call failed).
	// This allows consumers to parse the response without needing the proto schema.
	Response []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// Error message if the function call failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Metadata for correlation and identification.
	// Must match the meta from the corresponding EmitRequest.
	Meta          *StepMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponseRequest) Reset() {
	*x = EmitResponseRequest{}
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponseRequest) ProtoMessage() {}

func (x *EmitResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponseRequest.ProtoReflect.Descriptor instead.
func (*EmitResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP(), []int{2}
}

func (x *EmitResponseRequest) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *EmitResponseRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EmitResponseRequest) GetMeta() *StepMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EmitResponseResponse is empty - this is a fire-and-forget call.
type EmitResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponseResponse) Reset() {
	*x = EmitResponseResponse{}
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponseResponse) ProtoMessage() {}

func (x *EmitResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponseResponse.ProtoReflect.Descriptor instead.
func (*EmitResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP(), []int{3}
}

// StepMeta contains metadata for correlating and identifying a function
// invocation within a pipeline execution.
type StepMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID identifying the entire pipeline execution (all steps in one reconciliation).
	// All function invocations within a single reconciliation share the same trace_id.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// UUID identifying this specific function invocation.
	SpanId string `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Zero-based index of this step in the function pipeline.
	StepIndex int32 `protobuf:"varint,3,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	// Per-step counter incremented when a function requests additional resources and
	// needs to be re-run, starting from 0.
	Iteration int32 `protobuf:"varint,4,opt,name=iteration,proto3" json:"iteration,omitempty"`
	// Name of the function being invoked.
	FunctionName string `protobuf:"bytes,5,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// Name of the Composition defining this pipeline.
	CompositionName string `protobuf:"bytes,6,opt,name=composition_name,json=compositionName,proto3" json:"composition_name,omitempty"`
	// UID of the composite resource being reconciled.
	CompositeResourceUid string `protobuf:"bytes,7,opt,name=composite_resource_uid,json=compositeResourceUid,proto3" json:"composite_resource_uid,omitempty"`
	// Name of the composite resource being reconciled.
	CompositeResourceName string `protobuf:"bytes,8,opt,name=composite_resource_name,json=compositeResourceName,proto3" json:"composite_resource_name,omitempty"`
	// Namespace of the composite resource (empty for cluster-scoped resources).
	CompositeResourceNamespace string `protobuf:"bytes,9,opt,name=composite_resource_namespace,json=compositeResourceNamespace,proto3" json:"composite_resource_namespace,omitempty"`
	// API version of the composite resource (e.g., "example.org/v1").
	CompositeResourceApiVersion string `protobuf:"bytes,10,opt,name=composite_resource_api_version,json=compositeResourceApiVersion,proto3" json:"composite_resource_api_version,omitempty"`
	// Kind of the composite resource (e.g., "XDatabase").
	CompositeResourceKind string `protobuf:"bytes,11,opt,name=composite_resource_kind,json=compositeResourceKind,proto3" json:"composite_resource_kind,omitempty"`
	// Timestamp when this step was executed.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepMeta) Reset() {
	*x = StepMeta{}
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepMeta) ProtoMessage() {}

func (x *StepMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepMeta.ProtoReflect.Descriptor instead.
func (*StepMeta) Descriptor() ([]byte, []int) {
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP(), []int{4}
}

func (x *StepMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *StepMeta) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *StepMeta) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *StepMeta) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *StepMeta) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *StepMeta) GetCompositionName() string {
	if x != nil {
		return x.CompositionName
	}
	return ""
}

func (x *StepMeta) GetCompositeResourceUid() string {
	if x != nil {
		return x.CompositeResourceUid
	}
	return ""
}

func (x *StepMeta) GetCompositeResourceName() string {
	if x != nil {
		return x.CompositeResourceName
	}
	return ""
}

func (x *StepMeta) GetCompositeResourceNamespace() string {
	if x != nil {
		return x.CompositeResourceNamespace
	}
	return ""
}

func (x *StepMeta) GetCompositeResourceApiVersion() string {
	if x != nil {
		return x.CompositeResourceApiVersion
	}
	return ""
}

func (x *StepMeta) GetCompositeResourceKind() string {
	if x != nil {
		return x.CompositeResourceKind
	}
	return ""
}

func (x *StepMeta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_pipeline_v1alpha1_pipeline_inspector_proto protoreflect.FileDescriptor

const file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDesc = "" +
	"\n" +
	"0proto/pipeline/v1alpha1/pipeline_inspector.proto\x12\x1ccrossplane.pipeline.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x12EmitRequestRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\fR\arequest\x12:\n" +
	"\x04meta\x18\x02 \x01(\v2&.crossplane.pipeline.v1alpha1.StepMetaR\x04meta\"\x15\n" +
	"\x13EmitRequestResponse\"\x83\x01\n" +
	"\x13EmitResponseRequest\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\x04meta\x18\x03 \x01(\v2&.crossplane.pipeline.v1alpha1.StepMetaR\x04meta\"\x16\n" +
	"\x14EmitResponseResponse\"\xb2\x04\n" +
	"\bStepMeta\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1d\n" +
	"\n" +
	"step_index\x18\x03 \x01(\x05R\tstepIndex\x12\x1c\n" +
	"\titeration\x18\x04 \x01(\x05R\titeration\x12#\n" +
	"\rfunction_name\x18\x05 \x01(\tR\ffunctionName\x12)\n" +
	"\x10composition_name\x18\x06 \x01(\tR\x0fcompositionName\x124\n" +
	"\x16composite_resource_uid\x18\a \x01(\tR\x14compositeResourceUid\x126\n" +
	"\x17composite_resource_name\x18\b \x01(\tR\x15compositeResourceName\x12@\n" +
	"\x1ccomposite_resource_namespace\x18\t \x01(\tR\x1acompositeResourceNamespace\x12C\n" +
	"\x1ecomposite_resource_api_version\x18\n" +
	" \x01(\tR\x1bcompositeResourceApiVersion\x126\n" +
	"\x17composite_resource_kind\x18\v \x01(\tR\x15compositeResourceKind\x128\n" +
	"\ttimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x89\x02\n" +
	"\x18PipelineInspectorService\x12t\n" +
	"\vEmitRequest\x120.crossplane.pipeline.v1alpha1.EmitRequestRequest\x1a1.crossplane.pipeline.v1alpha1.EmitRequestResponse\"\x00\x12w\n" +
	"\fEmitResponse\x121.crossplane.pipeline.v1alpha1.EmitResponseRequest\x1a2.crossplane.pipeline.v1alpha1.EmitResponseResponse\"\x00B=Z;github.com/crossplane/crossplane/v2/proto/pipeline/v1alpha1b\x06proto3"

var (
	file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescOnce sync.Once
	file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescData []byte
)

func file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescGZIP() []byte {
	file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescOnce.Do(func() {
		file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDesc), len(file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDesc)))
	})
	return file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDescData
}

var file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_pipeline_v1alpha1_pipeline_inspector_proto_goTypes = []any{
	(*EmitRequestRequest)(nil),    // 0: crossplane.pipeline.v1alpha1.EmitRequestRequest
	(*EmitRequestResponse)(nil),   // 1: crossplane.pipeline.v1alpha1.EmitRequestResponse
	(*EmitResponseRequest)(nil),   // 2: crossplane.pipeline.v1alpha1.EmitResponseRequest
	(*EmitResponseResponse)(nil),  // 3: crossplane.pipeline.v1alpha1.EmitResponseResponse
	(*StepMeta)(nil),              // 4: crossplane.pipeline.v1alpha1.StepMeta
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_pipeline_v1alpha1_pipeline_inspector_proto_depIdxs = []int32{
	4, // 0: crossplane.pipeline.v1alpha1.EmitRequestRequest.meta:type_name -> crossplane.pipeline.v1alpha1.StepMeta
	4, // 1: crossplane.pipeline.v1alpha1.EmitResponseRequest.meta:type_name -> crossplane.pipeline.v1alpha1.StepMeta
	5, // 2: crossplane.pipeline.v1alpha1.StepMeta.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: crossplane.pipeline.v1alpha1.PipelineInspectorService.EmitRequest:input_type -> crossplane.pipeline.v1alpha1.EmitRequestRequest
	2, // 4: crossplane.pipeline.v1alpha1.PipelineInspectorService.EmitResponse:input_type -> crossplane.pipeline.v1alpha1.EmitResponseRequest
	1, // 5: crossplane.pipeline.v1alpha1.PipelineInspectorService.EmitRequest:output_type -> crossplane.pipeline.v1alpha1.EmitRequestResponse
	3, // 6: crossplane.pipeline.v1alpha1.PipelineInspectorService.EmitResponse:output_type -> crossplane.pipeline.v1alpha1.EmitResponseResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_pipeline_v1alpha1_pipeline_inspector_proto_init() }
func file_proto_pipeline_v1alpha1_pipeline_inspector_proto_init() {
	if File_proto_pipeline_v1alpha1_pipeline_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDesc), len(file_proto_pipeline_v1alpha1_pipeline_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pipeline_v1alpha1_pipeline_inspector_proto_goTypes,
		DependencyIndexes: file_proto_pipeline_v1alpha1_pipeline_inspector_proto_depIdxs,
		MessageInfos:      file_proto_pipeline_v1alpha1_pipeline_inspector_proto_msgTypes,
	}.Build()
	File_proto_pipeline_v1alpha1_pipeline_inspector_proto = out.File
	file_proto_pipeline_v1alpha1_pipeline_inspector_proto_goTypes = nil
	file_proto_pipeline_v1alpha1_pipeline_inspector_proto_depIdxs = nil
}
