//
//Copyright 2022 The Crossplane Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/fn/v1/run_function.proto

// This package defines the RPC for both composition and operation functions.
// Only composition functions are part of the 'apiextensions' API group. In
// retrospect this package should've been crossplane.proto.fn.v1, but it's too
// late to change it now.

//buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ready indicates whether a resource should be considered ready.
type Ready int32

const (
	Ready_READY_UNSPECIFIED Ready = 0
	// True means the resource has been observed to be ready.
	Ready_READY_TRUE Ready = 1
	// False means the resource has not been observed to be ready.
	Ready_READY_FALSE Ready = 2
)

// Enum value maps for Ready.
var (
	Ready_name = map[int32]string{
		0: "READY_UNSPECIFIED",
		1: "READY_TRUE",
		2: "READY_FALSE",
	}
	Ready_value = map[string]int32{
		"READY_UNSPECIFIED": 0,
		"READY_TRUE":        1,
		"READY_FALSE":       2,
	}
)

func (x Ready) Enum() *Ready {
	p := new(Ready)
	*p = x
	return p
}

func (x Ready) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ready) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fn_v1_run_function_proto_enumTypes[0].Descriptor()
}

func (Ready) Type() protoreflect.EnumType {
	return &file_proto_fn_v1_run_function_proto_enumTypes[0]
}

func (x Ready) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ready.Descriptor instead.
func (Ready) EnumDescriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{0}
}

// Severity of function results.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	// Fatal results are fatal; subsequent functions may run, but the function
	// pipeline run will be considered a failure and the first fatal result will
	// be returned as an error.
	Severity_SEVERITY_FATAL Severity = 1
	// Warning results are non-fatal; the entire pipeline will run to completion
	// but warning events and debug logs associated with the XR or Operation will
	// be emitted.
	Severity_SEVERITY_WARNING Severity = 2
	// Normal results are emitted as normal events and debug logs associated with
	// the XR or operation.
	Severity_SEVERITY_NORMAL Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_FATAL",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_NORMAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_FATAL":       1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_NORMAL":      3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fn_v1_run_function_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_fn_v1_run_function_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{1}
}

// Target of function results and conditions.
type Target int32

const (
	// If the target is unspecified, the result targets the XR.
	Target_TARGET_UNSPECIFIED Target = 0
	// Target the XR. Results that target the XR should include detailed, advanced
	// information.
	Target_TARGET_COMPOSITE Target = 1
	// Target the XR and the claim. Results that target the XR and the claim
	// should include only end-user friendly information.
	Target_TARGET_COMPOSITE_AND_CLAIM Target = 2
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "TARGET_UNSPECIFIED",
		1: "TARGET_COMPOSITE",
		2: "TARGET_COMPOSITE_AND_CLAIM",
	}
	Target_value = map[string]int32{
		"TARGET_UNSPECIFIED":         0,
		"TARGET_COMPOSITE":           1,
		"TARGET_COMPOSITE_AND_CLAIM": 2,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fn_v1_run_function_proto_enumTypes[2].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_proto_fn_v1_run_function_proto_enumTypes[2]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{2}
}

type Status int32

const (
	Status_STATUS_CONDITION_UNSPECIFIED Status = 0
	Status_STATUS_CONDITION_UNKNOWN     Status = 1
	Status_STATUS_CONDITION_TRUE        Status = 2
	Status_STATUS_CONDITION_FALSE       Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_CONDITION_UNSPECIFIED",
		1: "STATUS_CONDITION_UNKNOWN",
		2: "STATUS_CONDITION_TRUE",
		3: "STATUS_CONDITION_FALSE",
	}
	Status_value = map[string]int32{
		"STATUS_CONDITION_UNSPECIFIED": 0,
		"STATUS_CONDITION_UNKNOWN":     1,
		"STATUS_CONDITION_TRUE":        2,
		"STATUS_CONDITION_FALSE":       3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fn_v1_run_function_proto_enumTypes[3].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_fn_v1_run_function_proto_enumTypes[3]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{3}
}

// A RunFunctionRequest requests that the function be run.
type RunFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata pertaining to this request.
	Meta *RequestMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The observed state prior to invocation of a function pipeline. State passed
	// to each function is fresh as of the time the pipeline was invoked, not as
	// of the time each function was invoked.
	Observed *State `protobuf:"bytes,2,opt,name=observed,proto3" json:"observed,omitempty"`
	// Desired state according to a function pipeline. The state passed to a
	// particular function may have been accumulated by previous functions in the
	// pipeline.
	//
	// Note that the desired state must be a partial object with only the fields
	// that this function (and its predecessors in the pipeline) wants to have set
	// in the object. Copying a non-partial observed state to desired is most
	// likely not what you want to do. Leaving out fields that had been returned
	// as desired before will result in them being deleted from the objects in the
	// cluster.
	Desired *State `protobuf:"bytes,3,opt,name=desired,proto3" json:"desired,omitempty"`
	// Optional input specific to this function invocation. A JSON representation
	// of the 'input' block of the relevant entry in a function pipeline.
	Input *structpb.Struct `protobuf:"bytes,4,opt,name=input,proto3,oneof" json:"input,omitempty"`
	// Optional context. Crossplane may pass arbitrary contextual information to a
	// function. A function may also return context in its RunFunctionResponse,
	// and that context will be passed to subsequent functions. Crossplane
	// discards all context returned by the last function in the pipeline.
	Context *structpb.Struct `protobuf:"bytes,5,opt,name=context,proto3,oneof" json:"context,omitempty"`
	// Optional resources that the function specified in its requirements. Note
	// that resources is a map to Resources, plural. The map key corresponds to
	// the key in a RunFunctionResponse's requirements.extra_resources field. If a
	// function requested extra resources that did not exist, Crossplane sets
	// the map key to an empty Resources message to indicate that it attempted to
	// satisfy the request. This field is only populated when the function uses
	// extra_resources in its requirements.
	//
	// Deprecated: Use required_resources instead.
	//
	// Deprecated: Marked as deprecated in proto/fn/v1/run_function.proto.
	ExtraResources map[string]*Resources `protobuf:"bytes,6,rep,name=extra_resources,json=extraResources,proto3" json:"extra_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional credentials that this function may use to communicate with an
	// external system.
	Credentials map[string]*Credentials `protobuf:"bytes,7,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional resources that the function specified in its requirements. Note
	// that resources is a map to Resources, plural. The map key corresponds to
	// the key in a RunFunctionResponse's requirements.resources field. If a
	// function requested required resources that did not exist, Crossplane sets
	// the map key to an empty Resources message to indicate that it attempted to
	// satisfy the request. This field is only populated when the function uses
	// resources in its requirements.
	RequiredResources map[string]*Resources `protobuf:"bytes,8,rep,name=required_resources,json=requiredResources,proto3" json:"required_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunFunctionRequest) Reset() {
	*x = RunFunctionRequest{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFunctionRequest) ProtoMessage() {}

func (x *RunFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFunctionRequest.ProtoReflect.Descriptor instead.
func (*RunFunctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{0}
}

func (x *RunFunctionRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RunFunctionRequest) GetObserved() *State {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *RunFunctionRequest) GetDesired() *State {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *RunFunctionRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunFunctionRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/fn/v1/run_function.proto.
func (x *RunFunctionRequest) GetExtraResources() map[string]*Resources {
	if x != nil {
		return x.ExtraResources
	}
	return nil
}

func (x *RunFunctionRequest) GetCredentials() map[string]*Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *RunFunctionRequest) GetRequiredResources() map[string]*Resources {
	if x != nil {
		return x.RequiredResources
	}
	return nil
}

// Credentials that a function may use to communicate with an external system.
type Credentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source of the credentials.
	//
	// Types that are valid to be assigned to Source:
	//
	//	*Credentials_CredentialData
	Source        isCredentials_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetSource() isCredentials_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Credentials) GetCredentialData() *CredentialData {
	if x != nil {
		if x, ok := x.Source.(*Credentials_CredentialData); ok {
			return x.CredentialData
		}
	}
	return nil
}

type isCredentials_Source interface {
	isCredentials_Source()
}

type Credentials_CredentialData struct {
	// Credential data loaded by Crossplane, for example from a Secret.
	CredentialData *CredentialData `protobuf:"bytes,1,opt,name=credential_data,json=credentialData,proto3,oneof"`
}

func (*Credentials_CredentialData) isCredentials_Source() {}

// CredentialData loaded by Crossplane, for example from a Secret.
type CredentialData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string][]byte      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialData) Reset() {
	*x = CredentialData{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialData) ProtoMessage() {}

func (x *CredentialData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialData.ProtoReflect.Descriptor instead.
func (*CredentialData) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialData) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Resources represents the state of several Crossplane resources.
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Resource            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{3}
}

func (x *Resources) GetItems() []*Resource {
	if x != nil {
		return x.Items
	}
	return nil
}

// A RunFunctionResponse contains the result of a function run.
type RunFunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata pertaining to this response.
	Meta *ResponseMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Desired state according to a function pipeline. functions may add desired
	// state, and may mutate or delete any part of the desired state they are
	// concerned with. A function must pass through any part of the desired state
	// that it is not concerned with.
	//
	// Note that the desired state must be a partial object with only the fields
	// that this function (and its predecessors in the pipeline) wants to have set
	// in the object. Copying a non-partial observed state to desired is most
	// likely not what you want to do. Leaving out fields that had been returned
	// as desired before will result in them being deleted from the objects in the
	// cluster.
	Desired *State `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`
	// Results of the function run. Results are used for observability purposes.
	Results []*Result `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	// Optional context to be passed to the next function in the pipeline as part
	// of the RunFunctionRequest. Dropped on the last function in the pipeline.
	Context *structpb.Struct `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"`
	// Requirements that must be satisfied for this function to run successfully.
	Requirements *Requirements `protobuf:"bytes,5,opt,name=requirements,proto3" json:"requirements,omitempty"`
	// Status conditions to be applied to the XR. Conditions may also optionally
	// be applied to the XR's associated claim.
	//
	// Conditions are only used for composition. They're ignored by Operations.
	Conditions []*Condition `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Optional output specific to this function invocation.
	//
	// Only Operations use function output. XRs will discard any function output.
	Output        *structpb.Struct `protobuf:"bytes,7,opt,name=output,proto3,oneof" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFunctionResponse) Reset() {
	*x = RunFunctionResponse{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFunctionResponse) ProtoMessage() {}

func (x *RunFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFunctionResponse.ProtoReflect.Descriptor instead.
func (*RunFunctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{4}
}

func (x *RunFunctionResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RunFunctionResponse) GetDesired() *State {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *RunFunctionResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RunFunctionResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RunFunctionResponse) GetRequirements() *Requirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *RunFunctionResponse) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RunFunctionResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

// RequestMeta contains metadata pertaining to a RunFunctionRequest.
type RequestMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An opaque string identifying a request. Requests with identical tags will
	// be otherwise identical.
	Tag           string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{5}
}

func (x *RequestMeta) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Requirements that must be satisfied for a function to run successfully.
type Requirements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resources that this function requires. The map key uniquely identifies the
	// group of resources.
	//
	// Deprecated: Use resources instead.
	//
	// Deprecated: Marked as deprecated in proto/fn/v1/run_function.proto.
	ExtraResources map[string]*ResourceSelector `protobuf:"bytes,1,rep,name=extra_resources,json=extraResources,proto3" json:"extra_resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resources that this function requires. The map key uniquely identifies the
	// group of resources.
	Resources     map[string]*ResourceSelector `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirements) Reset() {
	*x = Requirements{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirements) ProtoMessage() {}

func (x *Requirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirements.ProtoReflect.Descriptor instead.
func (*Requirements) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in proto/fn/v1/run_function.proto.
func (x *Requirements) GetExtraResources() map[string]*ResourceSelector {
	if x != nil {
		return x.ExtraResources
	}
	return nil
}

func (x *Requirements) GetResources() map[string]*ResourceSelector {
	if x != nil {
		return x.Resources
	}
	return nil
}

// ResourceSelector selects a group of resources, either by name or by label.
type ResourceSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version of resources to select.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Kind of resources to select.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Resources to match.
	//
	// Types that are valid to be assigned to Match:
	//
	//	*ResourceSelector_MatchName
	//	*ResourceSelector_MatchLabels
	Match isResourceSelector_Match `protobuf_oneof:"match"`
	// Match resources in this namespace. Omit namespace to match cluster scoped
	// resources, or to match namespaced resources by labels across all
	// namespaces.
	Namespace     *string `protobuf:"bytes,5,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSelector) Reset() {
	*x = ResourceSelector{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSelector) ProtoMessage() {}

func (x *ResourceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSelector.ProtoReflect.Descriptor instead.
func (*ResourceSelector) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceSelector) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ResourceSelector) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceSelector) GetMatch() isResourceSelector_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *ResourceSelector) GetMatchName() string {
	if x != nil {
		if x, ok := x.Match.(*ResourceSelector_MatchName); ok {
			return x.MatchName
		}
	}
	return ""
}

func (x *ResourceSelector) GetMatchLabels() *MatchLabels {
	if x != nil {
		if x, ok := x.Match.(*ResourceSelector_MatchLabels); ok {
			return x.MatchLabels
		}
	}
	return nil
}

func (x *ResourceSelector) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type isResourceSelector_Match interface {
	isResourceSelector_Match()
}

type ResourceSelector_MatchName struct {
	// Match the resource with this name.
	MatchName string `protobuf:"bytes,3,opt,name=match_name,json=matchName,proto3,oneof"`
}

type ResourceSelector_MatchLabels struct {
	// Match all resources with these labels.
	MatchLabels *MatchLabels `protobuf:"bytes,4,opt,name=match_labels,json=matchLabels,proto3,oneof"`
}

func (*ResourceSelector_MatchName) isResourceSelector_Match() {}

func (*ResourceSelector_MatchLabels) isResourceSelector_Match() {}

// MatchLabels defines a set of labels to match resources against.
type MatchLabels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchLabels) Reset() {
	*x = MatchLabels{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchLabels) ProtoMessage() {}

func (x *MatchLabels) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchLabels.ProtoReflect.Descriptor instead.
func (*MatchLabels) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{8}
}

func (x *MatchLabels) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ResponseMeta contains metadata pertaining to a RunFunctionResponse.
type ResponseMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An opaque string identifying the content of the request. Must match the
	// meta.tag of the corresponding RunFunctionRequest.
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	// Time-to-live of this response. Crossplane will call the function again when
	// the TTL expires. Crossplane may cache the response to avoid calling the
	// function again until the TTL expires.
	Ttl           *durationpb.Duration `protobuf:"bytes,2,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseMeta) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ResponseMeta) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// State of the XR (XR) and any resources.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state of the XR (XR).
	Composite *Resource `protobuf:"bytes,1,opt,name=composite,proto3" json:"composite,omitempty"`
	// The state of any other resources. In composition functions these are the
	// composed resources. In operation functions they're arbitrary resources that
	// the operation wants to create or update.
	Resources     map[string]*Resource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{10}
}

func (x *State) GetComposite() *Resource {
	if x != nil {
		return x.Composite
	}
	return nil
}

func (x *State) GetResources() map[string]*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// A Resource represents the state of a Kubernetes resource.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON representation of the resource.
	//
	// * Crossplane will set this field in a RunFunctionRequest to the entire
	// observed state of a resource - including its metadata, spec, and status.
	//
	// * A function should set this field in a RunFunctionRequest to communicate
	// the desired state of the resource.
	//
	// * A function may only specify the desired status of a XR - not its metadata
	// or spec. A function should not return desired metadata or spec for a XR.
	// This will be ignored.
	//
	// * A function may not specify the desired status of any other resource -
	// e.g. composed resources. It may only specify their metadata and spec.
	// Status will be ignored.
	Resource *structpb.Struct `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The resource's connection details.
	//
	// * Crossplane will set this field in a RunFunctionRequest to communicate the
	// the observed connection details of a composite or composed resource.
	//
	// * A function should set this field in a RunFunctionResponse to indicate the
	// desired connection details of legacy XRs. For modern XRs, this will be ignored.
	//
	// * A function should not set this field in a RunFunctionResponse to indicate
	// the desired connection details of a composed resource. This will be
	// ignored.
	//
	// Connection details are only used for composition. They're ignored by
	// Operations.
	ConnectionDetails map[string][]byte `protobuf:"bytes,2,rep,name=connection_details,json=connectionDetails,proto3" json:"connection_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Ready indicates whether the resource should be considered ready.
	//
	// * Crossplane will never set this field in a RunFunctionRequest.
	//
	// * A function should set this field to READY_TRUE in a RunFunctionResponse
	// to indicate that a desired resource is ready.
	//
	// * A function should set this field to READY_TRUE in a RunFunctionResponse
	// to indicate that a desired XR is ready. This overwrites the standard
	// readiness detection that determines the ready state of the composite by the
	// ready state of the composed resources.
	//
	// Ready is only used for composition. It's ignored by Operations.
	Ready         Ready `protobuf:"varint,3,opt,name=ready,proto3,enum=apiextensions.fn.proto.v1.Ready" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{11}
}

func (x *Resource) GetResource() *structpb.Struct {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource) GetConnectionDetails() map[string][]byte {
	if x != nil {
		return x.ConnectionDetails
	}
	return nil
}

func (x *Resource) GetReady() Ready {
	if x != nil {
		return x.Ready
	}
	return Ready_READY_UNSPECIFIED
}

// A Result of running a function.
type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Severity of this result.
	Severity Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=apiextensions.fn.proto.v1.Severity" json:"severity,omitempty"`
	// Human-readable details about the result.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional PascalCase, machine-readable reason for this result. If omitted,
	// the value will be ComposeResources.
	Reason *string `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// The resources this result targets.
	Target        *Target `protobuf:"varint,4,opt,name=target,proto3,enum=apiextensions.fn.proto.v1.Target,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{12}
}

func (x *Result) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Result) GetTarget() Target {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return Target_TARGET_UNSPECIFIED
}

// Status condition to be applied to the XR. Condition may also optionally be
// applied to the XR's associated claim. For detailed information on proper
// usage of status conditions, please see
// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties.
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of condition in PascalCase.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Status of the condition.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=apiextensions.fn.proto.v1.Status" json:"status,omitempty"`
	// Reason contains a programmatic identifier indicating the reason for the
	// condition's last transition. Producers of specific condition types may
	// define expected values and meanings for this field, and whether the values
	// are considered a guaranteed API. The value should be a PascalCase string.
	// This field may not be empty.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Message is a human readable message indicating details about the
	// transition. This may be an empty string.
	Message *string `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// The resources this condition targets.
	Target        *Target `protobuf:"varint,5,opt,name=target,proto3,enum=apiextensions.fn.proto.v1.Target,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fn_v1_run_function_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_fn_v1_run_function_proto_rawDescGZIP(), []int{13}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_CONDITION_UNSPECIFIED
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Condition) GetTarget() Target {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return Target_TARGET_UNSPECIFIED
}

var File_proto_fn_v1_run_function_proto protoreflect.FileDescriptor

const file_proto_fn_v1_run_function_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/fn/v1/run_function.proto\x12\x19apiextensions.fn.proto.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd0\a\n" +
	"\x12RunFunctionRequest\x12:\n" +
	"\x04meta\x18\x01 \x01(\v2&.apiextensions.fn.proto.v1.RequestMetaR\x04meta\x12<\n" +
	"\bobserved\x18\x02 \x01(\v2 .apiextensions.fn.proto.v1.StateR\bobserved\x12:\n" +
	"\adesired\x18\x03 \x01(\v2 .apiextensions.fn.proto.v1.StateR\adesired\x122\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\x05input\x88\x01\x01\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x01R\acontext\x88\x01\x01\x12n\n" +
	"\x0fextra_resources\x18\x06 \x03(\v2A.apiextensions.fn.proto.v1.RunFunctionRequest.ExtraResourcesEntryB\x02\x18\x01R\x0eextraResources\x12`\n" +
	"\vcredentials\x18\a \x03(\v2>.apiextensions.fn.proto.v1.RunFunctionRequest.CredentialsEntryR\vcredentials\x12s\n" +
	"\x12required_resources\x18\b \x03(\v2D.apiextensions.fn.proto.v1.RunFunctionRequest.RequiredResourcesEntryR\x11requiredResources\x1ag\n" +
	"\x13ExtraResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.apiextensions.fn.proto.v1.ResourcesR\x05value:\x028\x01\x1af\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.apiextensions.fn.proto.v1.CredentialsR\x05value:\x028\x01\x1aj\n" +
	"\x16RequiredResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.apiextensions.fn.proto.v1.ResourcesR\x05value:\x028\x01B\b\n" +
	"\x06_inputB\n" +
	"\n" +
	"\b_context\"m\n" +
	"\vCredentials\x12T\n" +
	"\x0fcredential_data\x18\x01 \x01(\v2).apiextensions.fn.proto.v1.CredentialDataH\x00R\x0ecredentialDataB\b\n" +
	"\x06source\"\x92\x01\n" +
	"\x0eCredentialData\x12G\n" +
	"\x04data\x18\x01 \x03(\v23.apiextensions.fn.proto.v1.CredentialData.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"F\n" +
	"\tResources\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.apiextensions.fn.proto.v1.ResourceR\x05items\"\xe3\x03\n" +
	"\x13RunFunctionResponse\x12;\n" +
	"\x04meta\x18\x01 \x01(\v2'.apiextensions.fn.proto.v1.ResponseMetaR\x04meta\x12:\n" +
	"\adesired\x18\x02 \x01(\v2 .apiextensions.fn.proto.v1.StateR\adesired\x12;\n" +
	"\aresults\x18\x03 \x03(\v2!.apiextensions.fn.proto.v1.ResultR\aresults\x126\n" +
	"\acontext\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\acontext\x88\x01\x01\x12K\n" +
	"\frequirements\x18\x05 \x01(\v2'.apiextensions.fn.proto.v1.RequirementsR\frequirements\x12D\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2$.apiextensions.fn.proto.v1.ConditionR\n" +
	"conditions\x124\n" +
	"\x06output\x18\a \x01(\v2\x17.google.protobuf.StructH\x01R\x06output\x88\x01\x01B\n" +
	"\n" +
	"\b_contextB\t\n" +
	"\a_output\"\x1f\n" +
	"\vRequestMeta\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\xa9\x03\n" +
	"\fRequirements\x12h\n" +
	"\x0fextra_resources\x18\x01 \x03(\v2;.apiextensions.fn.proto.v1.Requirements.ExtraResourcesEntryB\x02\x18\x01R\x0eextraResources\x12T\n" +
	"\tresources\x18\x02 \x03(\v26.apiextensions.fn.proto.v1.Requirements.ResourcesEntryR\tresources\x1an\n" +
	"\x13ExtraResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.apiextensions.fn.proto.v1.ResourceSelectorR\x05value:\x028\x01\x1ai\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.apiextensions.fn.proto.v1.ResourceSelectorR\x05value:\x028\x01\"\xef\x01\n" +
	"\x10ResourceSelector\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\n" +
	"match_name\x18\x03 \x01(\tH\x00R\tmatchName\x12K\n" +
	"\fmatch_labels\x18\x04 \x01(\v2&.apiextensions.fn.proto.v1.MatchLabelsH\x00R\vmatchLabels\x12!\n" +
	"\tnamespace\x18\x05 \x01(\tH\x01R\tnamespace\x88\x01\x01B\a\n" +
	"\x05matchB\f\n" +
	"\n" +
	"_namespace\"\x94\x01\n" +
	"\vMatchLabels\x12J\n" +
	"\x06labels\x18\x01 \x03(\v22.apiextensions.fn.proto.v1.MatchLabels.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\fResponseMeta\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x120\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\x03ttl\x88\x01\x01B\x06\n" +
	"\x04_ttl\"\xfc\x01\n" +
	"\x05State\x12A\n" +
	"\tcomposite\x18\x01 \x01(\v2#.apiextensions.fn.proto.v1.ResourceR\tcomposite\x12M\n" +
	"\tresources\x18\x02 \x03(\v2/.apiextensions.fn.proto.v1.State.ResourcesEntryR\tresources\x1aa\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.apiextensions.fn.proto.v1.ResourceR\x05value:\x028\x01\"\xa8\x02\n" +
	"\bResource\x123\n" +
	"\bresource\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bresource\x12i\n" +
	"\x12connection_details\x18\x02 \x03(\v2:.apiextensions.fn.proto.v1.Resource.ConnectionDetailsEntryR\x11connectionDetails\x126\n" +
	"\x05ready\x18\x03 \x01(\x0e2 .apiextensions.fn.proto.v1.ReadyR\x05ready\x1aD\n" +
	"\x16ConnectionDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x06Result\x12?\n" +
	"\bseverity\x18\x01 \x01(\x0e2#.apiextensions.fn.proto.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01\x12>\n" +
	"\x06target\x18\x04 \x01(\x0e2!.apiextensions.fn.proto.v1.TargetH\x01R\x06target\x88\x01\x01B\t\n" +
	"\a_reasonB\t\n" +
	"\a_target\"\xe8\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.apiextensions.fn.proto.v1.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01\x12>\n" +
	"\x06target\x18\x05 \x01(\x0e2!.apiextensions.fn.proto.v1.TargetH\x01R\x06target\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_target*?\n" +
	"\x05Ready\x12\x15\n" +
	"\x11READY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"READY_TRUE\x10\x01\x12\x0f\n" +
	"\vREADY_FALSE\x10\x02*c\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_FATAL\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_NORMAL\x10\x03*V\n" +
	"\x06Target\x12\x16\n" +
	"\x12TARGET_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TARGET_COMPOSITE\x10\x01\x12\x1e\n" +
	"\x1aTARGET_COMPOSITE_AND_CLAIM\x10\x02*\x7f\n" +
	"\x06Status\x12 \n" +
	"\x1cSTATUS_CONDITION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STATUS_CONDITION_UNKNOWN\x10\x01\x12\x19\n" +
	"\x15STATUS_CONDITION_TRUE\x10\x02\x12\x1a\n" +
	"\x16STATUS_CONDITION_FALSE\x10\x032\x87\x01\n" +
	"\x15FunctionRunnerService\x12n\n" +
	"\vRunFunction\x12-.apiextensions.fn.proto.v1.RunFunctionRequest\x1a..apiextensions.fn.proto.v1.RunFunctionResponse\"\x00B1Z/github.com/crossplane/crossplane/v2/proto/fn/v1b\x06proto3"

var (
	file_proto_fn_v1_run_function_proto_rawDescOnce sync.Once
	file_proto_fn_v1_run_function_proto_rawDescData []byte
)

func file_proto_fn_v1_run_function_proto_rawDescGZIP() []byte {
	file_proto_fn_v1_run_function_proto_rawDescOnce.Do(func() {
		file_proto_fn_v1_run_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fn_v1_run_function_proto_rawDesc), len(file_proto_fn_v1_run_function_proto_rawDesc)))
	})
	return file_proto_fn_v1_run_function_proto_rawDescData
}

var file_proto_fn_v1_run_function_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_fn_v1_run_function_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_fn_v1_run_function_proto_goTypes = []any{
	(Ready)(0),                  // 0: apiextensions.fn.proto.v1.Ready
	(Severity)(0),               // 1: apiextensions.fn.proto.v1.Severity
	(Target)(0),                 // 2: apiextensions.fn.proto.v1.Target
	(Status)(0),                 // 3: apiextensions.fn.proto.v1.Status
	(*RunFunctionRequest)(nil),  // 4: apiextensions.fn.proto.v1.RunFunctionRequest
	(*Credentials)(nil),         // 5: apiextensions.fn.proto.v1.Credentials
	(*CredentialData)(nil),      // 6: apiextensions.fn.proto.v1.CredentialData
	(*Resources)(nil),           // 7: apiextensions.fn.proto.v1.Resources
	(*RunFunctionResponse)(nil), // 8: apiextensions.fn.proto.v1.RunFunctionResponse
	(*RequestMeta)(nil),         // 9: apiextensions.fn.proto.v1.RequestMeta
	(*Requirements)(nil),        // 10: apiextensions.fn.proto.v1.Requirements
	(*ResourceSelector)(nil),    // 11: apiextensions.fn.proto.v1.ResourceSelector
	(*MatchLabels)(nil),         // 12: apiextensions.fn.proto.v1.MatchLabels
	(*ResponseMeta)(nil),        // 13: apiextensions.fn.proto.v1.ResponseMeta
	(*State)(nil),               // 14: apiextensions.fn.proto.v1.State
	(*Resource)(nil),            // 15: apiextensions.fn.proto.v1.Resource
	(*Result)(nil),              // 16: apiextensions.fn.proto.v1.Result
	(*Condition)(nil),           // 17: apiextensions.fn.proto.v1.Condition
	nil,                         // 18: apiextensions.fn.proto.v1.RunFunctionRequest.ExtraResourcesEntry
	nil,                         // 19: apiextensions.fn.proto.v1.RunFunctionRequest.CredentialsEntry
	nil,                         // 20: apiextensions.fn.proto.v1.RunFunctionRequest.RequiredResourcesEntry
	nil,                         // 21: apiextensions.fn.proto.v1.CredentialData.DataEntry
	nil,                         // 22: apiextensions.fn.proto.v1.Requirements.ExtraResourcesEntry
	nil,                         // 23: apiextensions.fn.proto.v1.Requirements.ResourcesEntry
	nil,                         // 24: apiextensions.fn.proto.v1.MatchLabels.LabelsEntry
	nil,                         // 25: apiextensions.fn.proto.v1.State.ResourcesEntry
	nil,                         // 26: apiextensions.fn.proto.v1.Resource.ConnectionDetailsEntry
	(*structpb.Struct)(nil),     // 27: google.protobuf.Struct
	(*durationpb.Duration)(nil), // 28: google.protobuf.Duration
}
var file_proto_fn_v1_run_function_proto_depIdxs = []int32{
	9,  // 0: apiextensions.fn.proto.v1.RunFunctionRequest.meta:type_name -> apiextensions.fn.proto.v1.RequestMeta
	14, // 1: apiextensions.fn.proto.v1.RunFunctionRequest.observed:type_name -> apiextensions.fn.proto.v1.State
	14, // 2: apiextensions.fn.proto.v1.RunFunctionRequest.desired:type_name -> apiextensions.fn.proto.v1.State
	27, // 3: apiextensions.fn.proto.v1.RunFunctionRequest.input:type_name -> google.protobuf.Struct
	27, // 4: apiextensions.fn.proto.v1.RunFunctionRequest.context:type_name -> google.protobuf.Struct
	18, // 5: apiextensions.fn.proto.v1.RunFunctionRequest.extra_resources:type_name -> apiextensions.fn.proto.v1.RunFunctionRequest.ExtraResourcesEntry
	19, // 6: apiextensions.fn.proto.v1.RunFunctionRequest.credentials:type_name -> apiextensions.fn.proto.v1.RunFunctionRequest.CredentialsEntry
	20, // 7: apiextensions.fn.proto.v1.RunFunctionRequest.required_resources:type_name -> apiextensions.fn.proto.v1.RunFunctionRequest.RequiredResourcesEntry
	6,  // 8: apiextensions.fn.proto.v1.Credentials.credential_data:type_name -> apiextensions.fn.proto.v1.CredentialData
	21, // 9: apiextensions.fn.proto.v1.CredentialData.data:type_name -> apiextensions.fn.proto.v1.CredentialData.DataEntry
	15, // 10: apiextensions.fn.proto.v1.Resources.items:type_name -> apiextensions.fn.proto.v1.Resource
	13, // 11: apiextensions.fn.proto.v1.RunFunctionResponse.meta:type_name -> apiextensions.fn.proto.v1.ResponseMeta
	14, // 12: apiextensions.fn.proto.v1.RunFunctionResponse.desired:type_name -> apiextensions.fn.proto.v1.State
	16, // 13: apiextensions.fn.proto.v1.RunFunctionResponse.results:type_name -> apiextensions.fn.proto.v1.Result
	27, // 14: apiextensions.fn.proto.v1.RunFunctionResponse.context:type_name -> google.protobuf.Struct
	10, // 15: apiextensions.fn.proto.v1.RunFunctionResponse.requirements:type_name -> apiextensions.fn.proto.v1.Requirements
	17, // 16: apiextensions.fn.proto.v1.RunFunctionResponse.conditions:type_name -> apiextensions.fn.proto.v1.Condition
	27, // 17: apiextensions.fn.proto.v1.RunFunctionResponse.output:type_name -> google.protobuf.Struct
	22, // 18: apiextensions.fn.proto.v1.Requirements.extra_resources:type_name -> apiextensions.fn.proto.v1.Requirements.ExtraResourcesEntry
	23, // 19: apiextensions.fn.proto.v1.Requirements.resources:type_name -> apiextensions.fn.proto.v1.Requirements.ResourcesEntry
	12, // 20: apiextensions.fn.proto.v1.ResourceSelector.match_labels:type_name -> apiextensions.fn.proto.v1.MatchLabels
	24, // 21: apiextensions.fn.proto.v1.MatchLabels.labels:type_name -> apiextensions.fn.proto.v1.MatchLabels.LabelsEntry
	28, // 22: apiextensions.fn.proto.v1.ResponseMeta.ttl:type_name -> google.protobuf.Duration
	15, // 23: apiextensions.fn.proto.v1.State.composite:type_name -> apiextensions.fn.proto.v1.Resource
	25, // 24: apiextensions.fn.proto.v1.State.resources:type_name -> apiextensions.fn.proto.v1.State.ResourcesEntry
	27, // 25: apiextensions.fn.proto.v1.Resource.resource:type_name -> google.protobuf.Struct
	26, // 26: apiextensions.fn.proto.v1.Resource.connection_details:type_name -> apiextensions.fn.proto.v1.Resource.ConnectionDetailsEntry
	0,  // 27: apiextensions.fn.proto.v1.Resource.ready:type_name -> apiextensions.fn.proto.v1.Ready
	1,  // 28: apiextensions.fn.proto.v1.Result.severity:type_name -> apiextensions.fn.proto.v1.Severity
	2,  // 29: apiextensions.fn.proto.v1.Result.target:type_name -> apiextensions.fn.proto.v1.Target
	3,  // 30: apiextensions.fn.proto.v1.Condition.status:type_name -> apiextensions.fn.proto.v1.Status
	2,  // 31: apiextensions.fn.proto.v1.Condition.target:type_name -> apiextensions.fn.proto.v1.Target
	7,  // 32: apiextensions.fn.proto.v1.RunFunctionRequest.ExtraResourcesEntry.value:type_name -> apiextensions.fn.proto.v1.Resources
	5,  // 33: apiextensions.fn.proto.v1.RunFunctionRequest.CredentialsEntry.value:type_name -> apiextensions.fn.proto.v1.Credentials
	7,  // 34: apiextensions.fn.proto.v1.RunFunctionRequest.RequiredResourcesEntry.value:type_name -> apiextensions.fn.proto.v1.Resources
	11, // 35: apiextensions.fn.proto.v1.Requirements.ExtraResourcesEntry.value:type_name -> apiextensions.fn.proto.v1.ResourceSelector
	11, // 36: apiextensions.fn.proto.v1.Requirements.ResourcesEntry.value:type_name -> apiextensions.fn.proto.v1.ResourceSelector
	15, // 37: apiextensions.fn.proto.v1.State.ResourcesEntry.value:type_name -> apiextensions.fn.proto.v1.Resource
	4,  // 38: apiextensions.fn.proto.v1.FunctionRunnerService.RunFunction:input_type -> apiextensions.fn.proto.v1.RunFunctionRequest
	8,  // 39: apiextensions.fn.proto.v1.FunctionRunnerService.RunFunction:output_type -> apiextensions.fn.proto.v1.RunFunctionResponse
	39, // [39:40] is the sub-list for method output_type
	38, // [38:39] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_proto_fn_v1_run_function_proto_init() }
func file_proto_fn_v1_run_function_proto_init() {
	if File_proto_fn_v1_run_function_proto != nil {
		return
	}
	file_proto_fn_v1_run_function_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_fn_v1_run_function_proto_msgTypes[1].OneofWrappers = []any{
		(*Credentials_CredentialData)(nil),
	}
	file_proto_fn_v1_run_function_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_fn_v1_run_function_proto_msgTypes[7].OneofWrappers = []any{
		(*ResourceSelector_MatchName)(nil),
		(*ResourceSelector_MatchLabels)(nil),
	}
	file_proto_fn_v1_run_function_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_fn_v1_run_function_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_fn_v1_run_function_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fn_v1_run_function_proto_rawDesc), len(file_proto_fn_v1_run_function_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fn_v1_run_function_proto_goTypes,
		DependencyIndexes: file_proto_fn_v1_run_function_proto_depIdxs,
		EnumInfos:         file_proto_fn_v1_run_function_proto_enumTypes,
		MessageInfos:      file_proto_fn_v1_run_function_proto_msgTypes,
	}.Build()
	File_proto_fn_v1_run_function_proto = out.File
	file_proto_fn_v1_run_function_proto_goTypes = nil
	file_proto_fn_v1_run_function_proto_depIdxs = nil
}
