/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/crossplane/crossplane/apis/pkg/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigurationRevisions implements ConfigurationRevisionInterface
type FakeConfigurationRevisions struct {
	Fake *FakePkgV1
}

var configurationrevisionsResource = v1.SchemeGroupVersion.WithResource("configurationrevisions")

var configurationrevisionsKind = v1.SchemeGroupVersion.WithKind("ConfigurationRevision")

// Get takes name of the configurationRevision, and returns the corresponding configurationRevision object, and an error if there is any.
func (c *FakeConfigurationRevisions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ConfigurationRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(configurationrevisionsResource, name), &v1.ConfigurationRevision{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConfigurationRevision), err
}

// List takes label and field selectors, and returns the list of ConfigurationRevisions that match those selectors.
func (c *FakeConfigurationRevisions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ConfigurationRevisionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(configurationrevisionsResource, configurationrevisionsKind, opts), &v1.ConfigurationRevisionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ConfigurationRevisionList{ListMeta: obj.(*v1.ConfigurationRevisionList).ListMeta}
	for _, item := range obj.(*v1.ConfigurationRevisionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configurationRevisions.
func (c *FakeConfigurationRevisions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(configurationrevisionsResource, opts))
}

// Create takes the representation of a configurationRevision and creates it.  Returns the server's representation of the configurationRevision, and an error, if there is any.
func (c *FakeConfigurationRevisions) Create(ctx context.Context, configurationRevision *v1.ConfigurationRevision, opts metav1.CreateOptions) (result *v1.ConfigurationRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(configurationrevisionsResource, configurationRevision), &v1.ConfigurationRevision{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConfigurationRevision), err
}

// Update takes the representation of a configurationRevision and updates it. Returns the server's representation of the configurationRevision, and an error, if there is any.
func (c *FakeConfigurationRevisions) Update(ctx context.Context, configurationRevision *v1.ConfigurationRevision, opts metav1.UpdateOptions) (result *v1.ConfigurationRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(configurationrevisionsResource, configurationRevision), &v1.ConfigurationRevision{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConfigurationRevision), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigurationRevisions) UpdateStatus(ctx context.Context, configurationRevision *v1.ConfigurationRevision, opts metav1.UpdateOptions) (*v1.ConfigurationRevision, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(configurationrevisionsResource, "status", configurationRevision), &v1.ConfigurationRevision{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConfigurationRevision), err
}

// Delete takes name of the configurationRevision and deletes it. Returns an error if one occurs.
func (c *FakeConfigurationRevisions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(configurationrevisionsResource, name, opts), &v1.ConfigurationRevision{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigurationRevisions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(configurationrevisionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ConfigurationRevisionList{})
	return err
}

// Patch applies the patch and returns the patched configurationRevision.
func (c *FakeConfigurationRevisions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ConfigurationRevision, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(configurationrevisionsResource, name, pt, data, subresources...), &v1.ConfigurationRevision{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ConfigurationRevision), err
}
