name: Backport

on:
  # NOTE(negz): This is a risky target, but we run this action only when and if
  # a PR is closed, then filter down to specifically merged PRs. We also don't
  # invoke any scripts, etc from within the repo. I believe the fact that we'll
  # be able to review PRs before this runs makes this fairly safe.
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types: [closed]
  # See also commands.yml for the /backport triggered variant of this workflow.

permissions:  
  contents: read

jobs:
  # NOTE(negz): I tested many backport GitHub actions before landing on this
  # one. Many do not support merge commits, or do not support pull requests with
  # more than one commit. This one does. It also handily links backport PRs with
  # new PRs, and provides commentary and instructions when it can't backport.
  # Note that PRs _must_ be labelled before they're merged to trigger a backport.
  open-pr:
    permissions:
      contents: write  # for korthout/backport-action to create branch
      pull-requests: write  # for korthout/backport-action to create PR to backport
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Open Backport PR
        uses: korthout/backport-action@66065406958f46e82238fd59546f5a99e69e22aa # v4.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_workspace: ${{ github.workspace }}
